[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "0.21.0", features = ["std"] }
serde = "1.0"
hex = "0.4"
serde_json = "1.0"
bonsai-sdk = "0.7.0"
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.6" }
anyhow = "1.0.82"
ethers = "2.0.14"
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", branch = "release-0.8" }
bincode = "1.3.3"
clap = { version = "4.0", features = ["derive", "env"] }
tokio = { version = "1.35", features = ["full"] }
x509-parser  = "0.15.1"
env_logger = { version = "0.10" }
log = { version = "0.4" }